version: '3'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/web
    depends_on:
      - redis
      - portainer

  redis:
    image: redis
    depends_on:
      - portainer

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: