jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
          source venv/bin/activate
          pytest
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
