version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
        command: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r flask_app/requirements.txt
      - run:
        command: |
          source venv/bin/activate
          pytest
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  version: 2
  heroku_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
