jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
        name: Install Python dependencies in a venv
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - run:
        command: |
        . venv/bin/activate
        pytest
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
